config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :comic_books
  resources :purchases, only: [:show, :create]

  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic_book.rb
class ComicBook < ApplicationRecord
  belongs_to :user

  has_many :purchases
  has_many_attached :pictures, dependent: :destroy

  validates :name, :location, :quantity, :price, :description, presence: true, allow_blank: false
  validates :description, length: { minimum: 5, too_short: "Please type at least a 5 character long description", maximum: 500, too_long: "500 characters is the maximum allowed" }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  enum status: %w(accepted pending declined)
  after_initialize :set_default

  belongs_to :user
  belongs_to :comic_book

  validates :status, :value, presence: true

  def set_default
    self.status = "pending"
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :seller, class_name: 'User', foreign_key: :seller_id

  validates :description, presence: true
  validates :description, length: { minimum: 5, too_short: "Please type at least a 5 character long description", maximum: 500, too_long: "500 characters is the maximum allowed" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comic_books, dependent: :destroy
  has_many :purchases, dependent: :destroy

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comic_books_controller.rb
class ComicBooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_comic_book, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].blank?
      @comic_books = policy_scope(ComicBook)
    else
      @parameter = params[:search].downcase
      @comic_books = policy_scope(ComicBook).where("name ILIKE :search", search: "%#{@parameter}%")
    end
  end

  def new
    @comic_book = ComicBook.new
    authorize @comic_book
  end

  def create
    @comic_book = ComicBook.new(comic_book_params)

    @comic_book.user = current_user
    authorize @comic_book

    if @comic_book.save
      redirect_to comic_book_path(@comic_book)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @comic_book.update(comic_book_params)
      redirect_to @comic_book, notice: "Comic Book was succesfully updated."
    else
      render :edit
    end
  end

  def destroy
    @comic_book.destroy

    redirect_to comic_books_path
    # later it should redirect to dashboard
  end

  private

  def set_comic_book
    @comic_book = ComicBook.find(params[:id])
    authorize @comic_book
  end

  def comic_book_params
    params.require(:comic_book).permit(:series, :name, :issue, :release_date, :writer, :artist, :location, :quantity, :price, :condition, :description, pictures: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def show
    @purchase = Purchase.find(params[:id])
    @comic_book = @purchase.comic_book

    authorize @purchase
  end

  def create
    @comic_book = ComicBook.find(params[:comic_book])

    @purchase = Purchase.new

    @purchase.user = current_user
    @purchase.comic_book = @comic_book
    @purchase.value = @comic_book.price

    authorize @purchase

    if @purchase.save
      redirect_to purchase_path(@purchase)
    else
      flash[:alert] = "Not possible to buy"
      render "comic_books/show"
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:value)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @purchases = policy_scope(Purchase)
    authorize current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comic_books/_edit_form.html.erb
<%= simple_form_for @comic_book do |f| %>
  <%= f.input :series %>
  <%= f.input :name %>
  <%= f.input :issue %>
  <%= f.input :release_date %>
  <%= f.input :writer %>
  <%= f.input :artist %>
  <%= f.input :quantity %>
  <%= f.input :condition %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Edit your Comic Book"%>
<% end %>

app/views/comic_books/_new_form.html.erb
<%= simple_form_for @comic_book do |f| %>
  <%= f.input :series %>
  <%= f.input :name %>
  <%= f.input :issue %>
  <%= f.input :release_date %>
  <%= f.input :writer %>
  <%= f.input :artist %>
  <%= f.input :quantity %>
  <%= f.input :condition %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Add a Comic Book"%>
<% end %>

app/views/comic_books/edit.html.erb
<h1>Edit your Comic Book:</h1>

<%= render "edit_form", comic_book: @comic_book %>

app/views/comic_books/index.html.erb
<h1>The list of current comic books on sale:</h1>

<ul>
  <% @comic_books.each do |book| %>
      <li><%= link_to book.name, comic_book_path(book) %></li>
  <% end %>
</ul>

<%= link_to "Back to Home", root_path %>

app/views/comic_books/new.html.erb
<h1>Add your Comic Book to sell:</h1>

<%= render "new_form", comic_book: @comic_book %>

app/views/comic_books/show.html.erb
<h1>This comic book is on sale:</h1>

<div class="container">
  <ul>
    <% @comic_book.attributes.each do |attr| %>
      <li><%= attr %></li>
    <% end %>
  </ul>

  <% if @comic_book.pictures.attached? %>
    <% @comic_book.pictures.each do |picture| %>
      <%= cl_image_tag picture.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  <% else %>
    <p>No Foto...</p>
  <% end %>
</div>

<!-- Create Button to Buy -->
<div>
<p><%= link_to "Buy Comic Book", purchases_path(comic_book: @comic_book), method: :post %></p>
</div>

<% if !current_user.nil? && @comic_book.user_id == current_user.id %>
  <%= link_to "Edit", edit_comic_book_path(@comic_book) %>
  <%= link_to "Delete #{@comic_book.name}",
              comic_book_path(@comic_book),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicBookManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="container">
  <div class="banner d-flex justify-content-center align-items-center">
    <div class="banner-content">
      <p>Search for a Comic Book:</p>
      <label for="search" class="visuallyhidden">Search Comic Books</label>
      <input type="search" id="search" label="Search for Comic Books">
      <button type="submit">Search</button>
    </div>
  </div>


  <%= form_tag(comic_books_path, method: :get) do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Type", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", class: "btn btn-info glyphicon glyphicon-search", name: nil %>
      </div>
    </div>
  <% end %>







  <div class="d-flex justify-content-between">
    <div class="description">
      <p>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
  sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
  Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
  sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
  Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
      </p>
    </div>
    <%= image_tag("pic-home", height: "320", width: "460") %>
  </div>

  <div class="my-5 d-flex justify-content-center align-items-center">
    <div>
      <p>Sign up for free and start managing your collection</p>
      <div class="d-flex justify-content-center">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>

  <footer class="d-flex justify-content-between align-items-end">
    <div class="footer-links">
      <%= link_to "Facebook", "https://facebook.com", target: "_blank" %>
      <%= link_to "Facebook", "https://facebook.com", target: "_blank" %>
      <%= link_to "Facebook", "https://facebook.com", target: "_blank" %>
      <%= link_to "Facebook", "https://facebook.com", target: "_blank" %>
    </div>

    <p>This app was made with 🖤.</p>
  </footer>
</section>

app/views/purchases/_index.html.erb
<h1>My Purchases:</h1>

<% @purchases.each do |purchase| %>
  <%= purchase.comic_book.name %>
<% end %>

app/views/purchases/show.html.erb
<h1>You are buying <%= @comic_book.name %></h1>

<h2>Price: <%= @purchase.value %>€</h2>
<h2>Status: <%= @purchase.status %></h2>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/dashboard.html.erb
Olá, Hallo

<%= render "/purchases/index" %>